server:
  port: 8111
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/small_mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://open.alipay.com/develop/sandbox/app
#阿里沙箱支付配置
alipay:
  #应用ID
  appId: 9021000140695749
  #应用私钥
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCCmrr9BVhgn6ksGXVQuvw1UrtIEEQSdfCSn133jVZFqbMKrTJHrVu+WoR2g4Q+WOqRVz8pEeU0sQicznZEG9RmtpGLSd5JikD0HD+wbYyCKIlFRe7SPMrXwx/+xeSTYfzMtbRIG992GKbDY/T+eG/1MEldC859Qxc5LzedZshBh+P6lkzhg4+8VdKRmFzOA9cspo6jBgOgtyuKtQx4mp++2BRUaeoNaEOCrpXSHbPUs1ifmDJwTUfaEqb6QaFISv3ZDlJzVvmjQYrKzFVzE9Q3YummGfU2w2Mk6/61hRWil7YykWo3D9H/JVcg5YvfXZj4uNC81tLLk0Z0uz70z85ZAgMBAAECggEAN9fdGA7PCRF7jkWcadZpvIsRVPDPim0vXiISVaTzPHog+fGwTAGN9shRVzNIujfepCJ/+RmTvYHsws9sthaILRrnBH2jNCKPP1FM0i0lJQocF6idQvuHZ9Yguhj3cSU2qHkRCrwQQjisJWN5/8yTYm0xET3ZHqovJd5Qk1a9TXciyuijri1V4OjbJZOxkPAvSMOTFK3GQubkNjakTXw9DOvDfRYtyfoXq9sA+isILxzuD08F1710osisT1LUFme8/EM9jV9Q/6N0kElGSyEf5Wxf1+YqETh5+YVQl8iJlxltGhqaXL0rNuVPNi7D3aE/4O8pL5NhK7vTsd7gykWb+QKBgQDlqlpAytOuTsToO8QgdIdFap52m/c3xc1KgG+xNjwO7x4otIWGfjkBtvSKOOajwOiyuWiaMz0/ykvJUFESpatRx+edV1sfVFU5vcWtvPb5F7/22R1m+5m+S9l7KfqY3uYMXa2AYedJ/4RJEiWt+2whBCyEaC1xK1WW+YlReiZwNwKBgQCRlIUSjJnhoHHx5Um/JgAMS5a9YYxLLpqpnO1kuQAZDOQtpkWaUTDi6cI5KBQpSlujijwLlCHOW8YR+YmfKNjB5rkZadkwSNpV8zEYHPMBUvClG8EZ1HRTilj3mD9ce3VBpxGDs6cm9XJ68PemFgh6CVmAsI+4tyA4D/k1EvfN7wKBgB+sJJI25oZtWn5kb6HCMD2EfKIC1E8eujcCC2U3A4VTuKcIbjmkApyX7JV7T2NZ4T10kFZjppi7f0QeDXAy5LN8jBaIy4pAiRhTcYWKP80OV2zleEaRgBxcPXvcyDB43OTrrle8KLdtw4KIPCYIPFs5RiJkc4/d2AngE+3mmJJ1AoGBAIyD92HtFkaij/j04JbAvgEgILJQ6pJSvHQEhVrX+lEzkTbCq6IExhPvn0l99t/X5tXWgpiGdY7yJB+LZZubWIToBzeRZFJnr16Qqo1ku+VGQgKL5HnjCBjui2sIp/fDLm2dLZmamTdQaBxkZBUKZUotphdB1KdtEosqV9czpL4/AoGBAONRaMH1PeeYaAcY30UrCG8EQvQpB2dpDX2Ri/um4F+G/sHnqUiYxXv9FbS3moPrXqCND+C7KPN2If+luKzwc8pb2ygpHOaWtClHY9ySMB+LHh/J2AtZHzFao/YHOtGgRmYxw5l9oWLTpREBbqj+SsTKFiRgMR/iQdFIPYxl7GgN
  #支付宝公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjdqJqlpB/g7o0Cdq9XZ6TukaQitZAG+0BvqqGvhNKaMs1eSmHAtUYS0SWS6PRDS+Fp3QxwmyZ6NkXRHBrxaGwB6MiFtGX2QZJFh7DkFRbIK6jYAu16Vkn2MZNBDcXSPf+3XYVIj76RRGvTQogN0tSb0Crncg4BdrewYU6zwHkW/5YY4J5116ex43aVAep7MFd60alHyZZaEGk1yjNGpUS7RgjegUT+MlXaVEIOvLZbg7YrznNL8p3RUKNNSoCzYK7IXcMD9tABLiLZwSdfBdshSlwMPs43QvNl9GLMtSmbE0xJDp+8rHOCMc5bALfX46muPVkYCXs1ApkVO+NqiEGwIDAQAB
  #回调地址
  notifyUrl: http://gk8t3p.natappfree.cc/notify/
  #支付宝网关
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  #支付完跳转地址
  returnUrl: www.baidu.com
